### ISSUE TITLE
Identify and resolve all data warnings in transfomer

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/eosc-search-service#1236]
- [x] identify all current data input/output warnings (celery.logs)
- [x] resolve them, ignore them when needed

**Comment by wiktorflorian** [comment]
There are currently four warnings due to a mismatch of six column types:

- [ ] 1. service - output schema validation failure. Column types missmatch. Difference: `{'description': {'ACTUAL': 'string', 'EXPECTED': 'array<string>'}}`
- [ ] 2. interoperability guideline - output schema validation failure. Column types mismatch. Difference: `{'catalogue': {'ACTUAL': 'str', 'EXPECTED': 'string'}`, `'catalogues': {'ACTUAL': 'list', 'EXPECTED': 'array<string>'}`, `'uri': {'ACTUAL': 'NoneType', 'EXPECTED': 'list'}}`
- [ ] 3. catalogue - input schema validation failure. Column types missmatch. Difference: `{'legal_status': {'ACTUAL': 'string', 'EXPECTED': 'array<string>'}`, `'public_contacts': {'ACTUAL': 'array<struct<contactable_id:bigint,contactable_type:string,created_at:string,email:string,first_name:string,id:bigint,last_name:string,organisation:string,phone:string,position:string,updated_at:string>>', 'EXPECTED': 'array<struct<id:bigint,first_name:string,last_name:string,email:string,phone:string,position:string,organisation:string,contactable_type:string,contactable_id:bigint,created_at:string,updated_at:string>>'}}`
- [ ] 4. training - output schema validation failure. Column types missmatch. Difference: `{'resource_organisation': {'ACTUAL': 'array<string>', 'EXPECTED': 'string'}}`

**Comment by wiktorflorian** [comment]
I made all changes except for 'uri' in the interoperability guideline output schema. This is because there are currently no data containing 'uri', and the warning should disappear after at least one guideline containing 'uri' appears.

Furthermore, I will create a ticket because the 'legal_status' field in the catalogue output schema has been changed to 'string' to match MP, but in the Solr schema, it remains as 'strings'. Therefore, we need to modify the logic in the Solr schema and on the frontend. This matter is not urgent.
