### ISSUE TITLE
Finish live update

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/eosc-search-service#1307]
Scope:
- [x] debug suspend in providers - why event though all tasks are successful, the provider is not deleted from solr?
- [x] if data source is updated we need to check if in our solr service with the same ID exists - if so, delete that service and proceed with data source update task
- [x]  if service is updated we need to check if in our solr data source with the same ID exists - if so, delete that data source and proceed with service update task

**Comment by wiktorflorian** [comment]
In case of providers there were 2 issues. The first issue was that, upon suspending or deactivating a provider, the MP sen four tasks: three with `delete_data_by_id` and one `update`. The `update` task started simultaneously with the others but took longer to execute, resulting in no changes in Solr. The second issue involved incorrect behavior of the function `delete_data_by_id` due to an error in its implementation. It was only deleting records from the first collection, typically `all_collection`. This issue has been corrected with my PR.

![Screenshot 2024-04-24 at 11 19 25](https://github.com/cyfronet-fid/eosc-search-service/assets/127978878/f32d84a1-4328-4998-950b-6a343d245163)

Additionally, my PR includes logic to handle updates to the data source and service
