### ISSUE TITLE
Improve the autocomplete in Search Service

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#324]
Improve the behavior of the autocomplete, for eg.
- [ ] when I type "amnes" I see nothing but I would like to see "amnesia"
- [ ] I would like to see also "amnesia" when I write this word with misspellings for eg "amnesya"
- [x] when I am on the all catalog tab and I write "amnes" I can see two two clues from two tabs called "PUBLICATION"
![image](https://user-images.githubusercontent.com/43000481/201077187-6d001cf9-948b-4bf2-b5fc-c3c9c6aca44a.png)
the first one probably refers to all catalog and I would like to ask you to REMOVE it

**Comment by biometricsmw** [comment]
Hi @agpul, could you please check whether this duplication is still an issue? I checked with "amnes" word with the latest version of the app... and cannot observe the problem (please see attached screenshot). 
![Screenshot 2022-11-17 123020](https://user-images.githubusercontent.com/11648507/202435246-bc16ac7b-5143-4bfd-ae08-8f12f4c1be38.png)

**Comment by agpul** [comment]
@biometricsmw you are right, so this bug is resolved

**Comment by biometricsmw** [comment]
In this part, yup, exactly :) But two others are still in progress :)

**Comment by biometricsmw** [comment]
Hi @agpul, as an attachment to this comment I placed an example how the search works for now. As an example, I placed "Cases focarditis" instead of "Case of carditis". Could you please tell me whether such results are acceptable or should I try something to narrow them down? Thanks in advance for your response and opinion! 
![Screenshot 2022-11-18 135344](https://user-images.githubusercontent.com/11648507/202710093-d5c9e357-27f9-403e-8fe5-710e302825fb.png)

**Comment by agpul** [comment]
@biometricsmw Looks ok, but I need to test it on the PR to be 100% sure :) so please make a PR and ma and @Marcelinna will test it.

**Comment by biometricsmw** [comment]
Sure! I will just check one more strategy and then prepare a PR :)
