### ISSUE TITLE
Add an advanced search mechanism

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#558]

**Comment by eldenkat** [comment]
non relatable

**Comment by eldenkat** [comment]
Steps to reproduce the behavior:
1. Go to 'search service'
2. Enter "batteries" in the main bar
3. Go to "narrow your search" bar.
4. Pick "author" and add the name "aldrich" 
![2023-06-26](https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/59cd8273-4e54-4079-af6a-a07d5ba0e38d)
5. Change "all catalogs" to "software" in the drop-down list.
6. See "no data" output (correct)                     ![2023-06-26 (1)](https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/6e9c46f5-8581-4378-8445-9bb9cb3df6b4)
7. Leave software in drop-down list and pick software from the upper bar 
8. See 58 outputs                             
![2023-06-26 (3)](https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/86cd0b83-4c08-42aa-90dc-a800f755cdd6)
9. Change "software" to "all catalogs" in drop-down list.
10. See see the saved query, and yet the result is 2632 items                                     
![2023-06-26 (4)](https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/1c1de175-ed9e-4e92-b35f-cf7ebb6e071f)

 

**Expected behavior**
Fix the bug

**Comment by eldenkat** [comment]
no relevance
